#!/usr/bin/env python

# author bianyue

import os
import sys

command = sys.argv[1]
current_dir = os.getcwd()

projects = os.listdir(current_dir)

for project in projects:
    project_dir = current_dir + "/" + project
    if ".git" in os.listdir(project_dir):

        print('\033[1;31;40m')
        print('*' * 50)
        print "project:" + project
        os.chdir(project_dir)

        print('\033[1;35;40m')
        print command

        print('\033[1;37;40m')
        os.system(command)
        print('\033[1;31;40m')
        print('*' * 50)
        print('\033[0m')
